// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIpsZ8P7GV_PuG1pL4o7J9IsEBxSVL1F4',
    appId: '1:972679258794:web:28a6c4644c84700a4a66d3',
    messagingSenderId: '972679258794',
    projectId: 'pingolearn-71214',
    authDomain: 'pingolearn-71214.firebaseapp.com',
    storageBucket: 'pingolearn-71214.appspot.com',
    measurementId: 'G-LBDZN43CP2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5vNvps2PsDbz92TZ5l_LtJcfccvaeRX8',
    appId: '1:972679258794:android:2abdab4bf907f4bd4a66d3',
    messagingSenderId: '972679258794',
    projectId: 'pingolearn-71214',
    storageBucket: 'pingolearn-71214.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD1StWe8ds9MfxTBJhbTN6qY0Klbke-qjU',
    appId: '1:972679258794:ios:fadf631e98ea666b4a66d3',
    messagingSenderId: '972679258794',
    projectId: 'pingolearn-71214',
    storageBucket: 'pingolearn-71214.appspot.com',
    iosClientId: '972679258794-tvt97vgqdknafgqfnhuoks0khmq5hrdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingolearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD1StWe8ds9MfxTBJhbTN6qY0Klbke-qjU',
    appId: '1:972679258794:ios:fadf631e98ea666b4a66d3',
    messagingSenderId: '972679258794',
    projectId: 'pingolearn-71214',
    storageBucket: 'pingolearn-71214.appspot.com',
    iosClientId: '972679258794-tvt97vgqdknafgqfnhuoks0khmq5hrdg.apps.googleusercontent.com',
    iosBundleId: 'com.example.pingolearn',
  );
}
